"""Churn Prediction schemas."""
from typing import Optional
from pydantic import BaseModel, Field


class ChurnFeatures(BaseModel):
    Transaction_Count: float = Field(..., example=12.0)
    Total_Spend: float = Field(..., example=850.5)
    Avg_Order_Value: float = Field(..., example=70.87)
    Std_Order_Value: float = Field(default=20.0, example=20.0)
    Frequency: float = Field(..., example=1.2)
    Customer_Tenure_Days: float = Field(..., example=365.0)
    Transactions_Per_Month: float = Field(default=1.0, example=1.0)
    Customer_LTV: float = Field(default=850.0, example=850.0)
    Avg_Days_Between_Purchases: float = Field(default=30.0, example=30.0)
    Order_Value_CV: float = Field(default=0.28, example=0.28)
    Frequency_Score: float = Field(default=3.0, example=3.0)
    Monetary_Score: float = Field(default=3.0, example=3.0)
    Historical_Txn_Count: float = Field(default=12.0, example=12.0)
    Historical_Spend: float = Field(default=850.0, example=850.0)
    Preferred_Hour: float = Field(default=14.0, example=14.0)
    Weekend_Purchase_Pct: float = Field(default=0.3, example=0.3)
    Preferred_Day_Encoded: float = Field(default=2.0, example=2.0)
    Unique_Categories: float = Field(default=4.0, example=4.0)
    Category_Entropy: float = Field(default=1.5, example=1.5)
    Unique_Brands: float = Field(default=6.0, example=6.0)
    Avg_Rating: float = Field(default=4.0, example=4.0)
    Std_Rating: float = Field(default=0.8, example=0.8)
    Min_Rating: float = Field(default=2.0, example=2.0)
    Max_Rating: float = Field(default=5.0, example=5.0)
    Is_Satisfied_Customer: float = Field(default=1.0, example=1.0)
    Payment_Method_Changes: float = Field(default=1.0, example=1.0)
    Shipping_Method_Changes: float = Field(default=0.0, example=0.0)
    Pct_Shipped: float = Field(default=0.85, example=0.85)
    Pct_Processing: float = Field(default=0.05, example=0.05)
    Pct_Cancelled: float = Field(default=0.10, example=0.10)
    Avg_Cart_Size: float = Field(default=2.5, example=2.5)
    Max_Cart_Size: float = Field(default=5.0, example=5.0)
    Std_Cart_Size: float = Field(default=1.2, example=1.2)
    Age: float = Field(default=35.0, example=35.0)
